# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandal" do
  version "2.2.5"

  on_macos do
    on_arm do
      sha256 "23dcbd0f3ca7e003ba56959e2ada26d5a046aa1de78b4f5c00906b54fec8f0be"
      url "https://github.com/ahmetozer/sandal/releases/download/v#{version}/sandal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "sandal"
  desc "Lightweight portable container environment controller with macOS VM support"
  homepage "https://github.com/ahmetozer/sandal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandal"]
    end
  end

  # No zap stanza required

end
