# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandal" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "af66f7123af2ca85c1fb71df1fa83a948f7d8c50a967aeee924ad45e2f240211"
      url "https://github.com/ahmetozer/sandal/releases/download/v#{version}/sandal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "sandal"
  desc "Lightweight portable container environment controller with macOS VM support"
  homepage "https://github.com/ahmetozer/sandal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandal"]
    end
  end

  # No zap stanza required

end
