# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandal" do
  version "2.3.0"

  on_macos do
    on_arm do
      sha256 "f28e4b3a28920a644c0a766eccb90a980497aed4224aafaea7f0bd7f00e61468"
      url "https://github.com/ahmetozer/sandal/releases/download/v#{version}/sandal_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "sandal"
  desc "Lightweight portable container environment controller with macOS VM support"
  homepage "https://github.com/ahmetozer/sandal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandal"]
    end
  end

  # No zap stanza required

end
